### ISSUE TITLE
번역이 되질 않습니다

### ISSUE THREAD

**Issue by DrakedogX** [acidsound/transplus#3]
버튼을 눌러도 반응이 없더군요...

**Comment by acidsound** [comment]
v2로 판올림하였습니다.

**Comment by webhacking** [comment]
@acidsound 현재 저도 위와 같은 현상이 발생하는데, 요청한 대상의 서버에 응답 값을 보니 `Over Quota`라네요.

**Comment by BongJaeChoi** [comment]
Failed to load https://goxcors.appspot.com/cors?method=GET&url=https://translate.google.com: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://acidsound.github.io' is therefore not allowed access. The response had HTTP status code 503. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

콘솔에 에러가 찍히면서 번역이 되지않네요.

**Comment by acidsound** [comment]
addThis 플러그인에 문제가 있어 일단 순서를 바꾸었고 중간 번역 쪽이 작동하지 않는 쪽은 내용을 확인해봐야겠네요.

**Comment by acidsound** [comment]
현재 정상 작동합니다. addThis 쪽의 오류는 파악이 되지 않지만 정상적으로 공유가 됩니다.
